# Generated by Django 2.1.5 on 2019-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=40)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
