# Generated by Django 2.1.5 on 2019-02-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('verification', models.BooleanField()),
            ],
        ),
    ]
